---
- hosts: all
  vars:
    mail_services:
      - postfix
      - dovecot
  tasks:
    - name: Postfix and dovecot are running
      service:
        name: "{{ item }}"
        state: started
      loop: "{{ mail_services }}"
