---
- hosts: webservers
  gather_facts:yes
  task:
    - name: here we are checking ansible_hostname
      debug:
        msg: "hostname is {{ ansible_hostname }}"
    - name: here we are cheking inventory_hostname
      debug:
        msg: "hostname is {{ inventory_hostname }}"
