---
- hosts: seoul
  tasks:
    - name: Show various Ansible facts
      debug:
        msg: >
          The seoul of package is {{ package }}


- hosts: busan
  tasks:
  - name: Show various Ansible facts
    debug:
      msg: >
        The busan of package is {{ package }}
